Members Command - MF 5 Implementation
Dans-Plugins/Medieval-Factions pull request #1424
Opened 2022-08-03 05:46 UTC by dmccoystephenson

The info command will send the player a list of the members in their faction.

2022-08-03 07:00 UTC, alyphen requested changes

2022-08-20 15:35 UTC, dmccoystephenson commented on src/main/kotlin/com/dansplugins/factionsystem/command/faction/MfFactionCommand.kt
> +import com.dansplugins.factionsystem.faction.MfFactionMember
Nope! Good catch!

2022-08-20 15:36 UTC, dmccoystephenson commented on src/main/kotlin/com/dansplugins/factionsystem/command/faction/MfFactionCommand.kt
> +import com.dansplugins.factionsystem.faction.MfFactionMember
This has been removed.

2022-08-25 02:40 UTC, dmccoystephenson commented on src/main/kotlin/com/dansplugins/factionsystem/command/faction/members/MfFactionMembersCommand.kt
> +            }
What does your suggested implementation do? Does it print it with no new lines?

2022-08-25 07:11 UTC, alyphen commented on src/main/kotlin/com/dansplugins/factionsystem/command/faction/members/MfFactionMembersCommand.kt
> +            }
Breaks members into groups of 20 and then prints up to 20 members per line

2022-08-29 04:56 UTC, dmccoystephenson commented on src/main/kotlin/com/dansplugins/factionsystem/command/faction/members/MfFactionMembersCommand.kt
> +            }
I've added a role permission here. Please let me know if I've done it correctly.

2022-08-29 08:34 UTC, alyphen commented on src/main/kotlin/com/dansplugins/factionsystem/command/faction/members/MfFactionMembersCommand.kt
> +            }
Role permissions also need to be added to:
* MfFactionPermission.kt: permission constant, valueOf method for lookup, and values method for retrieving all values
* MfFaction.kt: default permission values
* MfFactionRoles.kt: default role settings

The constant from MfFactionRoles can then be imported.
I tend to write permissions there with action words - i.e. "Change name", "Add law", "Set flag", "View info", "Chat" - so for this one I think "VIEW_MEMBERS" would likely be a better name than "MEMBERS"

2022-08-29 18:41 UTC, dmccoystephenson commented on src/main/kotlin/com/dansplugins/factionsystem/command/faction/members/MfFactionMembersCommand.kt
> +            }
Thank you for this! The LIST_MEMBERS role permission should be all set now.

2022-08-29 18:42 UTC, dmccoystephenson commented on src/main/kotlin/com/dansplugins/factionsystem/command/faction/members/MfFactionMembersCommand.kt
> +            }
This should now print all of the members on the same line.

2022-08-29 19:33 UTC, alyphen commented on src/main/kotlin/com/dansplugins/factionsystem/command/faction/members/MfFactionMembersCommand.kt
> +            }
Perhaps ```faction.members.joinToString { it.player.toBukkit().name }``` would be more succinct?

2022-08-29 19:34 UTC, alyphen commented on src/main/kotlin/com/dansplugins/factionsystem/command/faction/members/MfFactionMembersCommand.kt
> +            }
Nice job :)

2022-09-11 16:46 UTC, dmccoystephenson commented on src/main/kotlin/com/dansplugins/factionsystem/command/faction/members/MfFactionMembersCommand.kt
> +            }
This has been made more succinct.

2022-09-11 16:48 UTC, alyphen approved these changes

2022-09-11 16:49 UTC, merged