Display Relationships in Info Command Output
Dans-Plugins/Medieval-Factions pull request #1623
Opened 2022-11-29 03:34 UTC by dmccoystephenson

The changes in this PR allow players to view the vassals, allies and enemies of a faction through the 'mf info' command.

2022-11-29 03:34 UTC, dmccoystephenson commented
closes #1600

2022-11-29 09:27 UTC, alyphen commented
Code looks good, just needs translations.
British is the same as American for these.

We can ask the Discord for German/French or look at existing translations to find which words have been used there. This shouldn't be a complex one since it's just singular words.

2022-12-03 19:49 UTC, dmccoystephenson commented
French translations are required for the following:

CommandFactionInfoVassalsTitle=Vassals:
CommandFactionInfoAlliesTitle=Allies:
CommandFactionInfoEnemiesTitle=Enemies:

2022-12-15 15:47 UTC, alyphen requested changes

2022-12-15 15:47 UTC, alyphen commented on src/main/resources/lang/lang_fr_FR.properties
> +CommandFactionInfoAlliesTitle=Alli�s:
Accent hasn't been committed properly

2022-12-15 15:47 UTC, alyphen commented on src/main/kotlin/com/dansplugins/factionsystem/command/faction/info/MfFactionInfoCommand.kt
> +                    sender.sendMessage("${BukkitChatColor.WHITE}${plugin.language["CommandFactionInfoVassalsTitle"]}") // TODO: add translation
Todos should be removed

2022-12-15 22:57 UTC, dmccoystephenson commented on src/main/resources/lang/lang_fr_FR.properties
> +CommandFactionInfoAlliesTitle=Alli�s:
I'm not sure how to resolve this.

2022-12-15 23:16 UTC, dmccoystephenson commented on src/main/kotlin/com/dansplugins/factionsystem/command/faction/info/MfFactionInfoCommand.kt
> +                    sender.sendMessage("${BukkitChatColor.WHITE}${plugin.language["CommandFactionInfoVassalsTitle"]}") // TODO: add translation
These have been removed.

2023-01-05 01:54 UTC, closed without merging